<?php

namespace Cms\Model\Mail\Definition;

/**
 * @method \Cms\Model\Mail\Definition\Query limit($limit = null)
 * @method \Cms\Model\Mail\Definition\Query offset($offset = null)
 * @method \Cms\Model\Mail\Definition\Query orderAsc($fieldName, $tableName = null)
 * @method \Cms\Model\Mail\Definition\Query orderDesc($fieldName, $tableName = null)
 * @method \Cms\Model\Mail\Definition\Query andQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Mail\Definition\Query whereQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Mail\Definition\Query orQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Mail\Definition\Query resetOrder()
 * @method \Cms\Model\Mail\Definition\Query resetWhere()
 * @method \Cms\Model\Mail\Definition\Query\Field whereId()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldId()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldId()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscId()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescId()
 * @method \Cms\Model\Mail\Definition\Query\Field whereLang()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldLang()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldLang()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscLang()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescLang()
 * @method \Cms\Model\Mail\Definition\Query\Field whereCmsMailServerId()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldCmsMailServerId()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldCmsMailServerId()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscCmsMailServerId()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescCmsMailServerId()
 * @method \Cms\Model\Mail\Definition\Query\Field whereName()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldName()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldName()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscName()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescName()
 * @method \Cms\Model\Mail\Definition\Query\Field whereReplyTo()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldReplyTo()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldReplyTo()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscReplyTo()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescReplyTo()
 * @method \Cms\Model\Mail\Definition\Query\Field whereFromName()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldFromName()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldFromName()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscFromName()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescFromName()
 * @method \Cms\Model\Mail\Definition\Query\Field whereSubject()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldSubject()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldSubject()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscSubject()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescSubject()
 * @method \Cms\Model\Mail\Definition\Query\Field whereMessage()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldMessage()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldMessage()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscMessage()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescMessage()
 * @method \Cms\Model\Mail\Definition\Query\Field whereHtml()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldHtml()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldHtml()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscHtml()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescHtml()
 * @method \Cms\Model\Mail\Definition\Query\Field whereDateAdd()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldDateAdd()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldDateAdd()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscDateAdd()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescDateAdd()
 * @method \Cms\Model\Mail\Definition\Query\Field whereDateModify()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldDateModify()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldDateModify()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscDateModify()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescDateModify()
 * @method \Cms\Model\Mail\Definition\Query\Field whereActive()
 * @method \Cms\Model\Mail\Definition\Query\Field andFieldActive()
 * @method \Cms\Model\Mail\Definition\Query\Field orFieldActive()
 * @method \Cms\Model\Mail\Definition\Query\Field orderAscActive()
 * @method \Cms\Model\Mail\Definition\Query\Field orderDescActive()
 * @method \Cms\Model\Mail\Definition\Query\Field andField($fieldName, $tableName = null)
 * @method \Cms\Model\Mail\Definition\Query\Field where($fieldName, $tableName = null)
 * @method \Cms\Model\Mail\Definition\Query\Field orField($fieldName, $tableName = null)
 * @method \Cms\Model\Mail\Definition\Query\Join join($tableName, $targetTableName = null)
 * @method \Cms\Model\Mail\Definition\Query\Join joinLeft($tableName, $targetTableName = null)
 * @method \Cms\Model\Mail\Definition\Record[] find()
 * @method \Cms\Model\Mail\Definition\Record findFirst()
 * @method \Cms\Model\Mail\Definition\Record findPk($value)
 */
class Query extends \Mmi\Dao\Query {

	/**
	 * @return \Cms\Model\Mail\Definition\Query
	 */
	public static function factory($daoClassName = null) {
		return new self($daoClassName);
	}

}
