<?php

namespace Cms\Model\Contact;

/**
 * @method \Cms\Model\Contact\Query limit($limit = null)
 * @method \Cms\Model\Contact\Query offset($offset = null)
 * @method \Cms\Model\Contact\Query orderAsc($fieldName, $tableName = null)
 * @method \Cms\Model\Contact\Query orderDesc($fieldName, $tableName = null)
 * @method \Cms\Model\Contact\Query andQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Contact\Query whereQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Contact\Query orQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Contact\Query resetOrder()
 * @method \Cms\Model\Contact\Query resetWhere()
 * @method \Cms\Model\Contact\Query\Field whereId()
 * @method \Cms\Model\Contact\Query\Field andFieldId()
 * @method \Cms\Model\Contact\Query\Field orFieldId()
 * @method \Cms\Model\Contact\Query\Field orderAscId()
 * @method \Cms\Model\Contact\Query\Field orderDescId()
 * @method \Cms\Model\Contact\Query\Field whereCmsContactOptionId()
 * @method \Cms\Model\Contact\Query\Field andFieldCmsContactOptionId()
 * @method \Cms\Model\Contact\Query\Field orFieldCmsContactOptionId()
 * @method \Cms\Model\Contact\Query\Field orderAscCmsContactOptionId()
 * @method \Cms\Model\Contact\Query\Field orderDescCmsContactOptionId()
 * @method \Cms\Model\Contact\Query\Field whereDateAdd()
 * @method \Cms\Model\Contact\Query\Field andFieldDateAdd()
 * @method \Cms\Model\Contact\Query\Field orFieldDateAdd()
 * @method \Cms\Model\Contact\Query\Field orderAscDateAdd()
 * @method \Cms\Model\Contact\Query\Field orderDescDateAdd()
 * @method \Cms\Model\Contact\Query\Field whereText()
 * @method \Cms\Model\Contact\Query\Field andFieldText()
 * @method \Cms\Model\Contact\Query\Field orFieldText()
 * @method \Cms\Model\Contact\Query\Field orderAscText()
 * @method \Cms\Model\Contact\Query\Field orderDescText()
 * @method \Cms\Model\Contact\Query\Field whereReply()
 * @method \Cms\Model\Contact\Query\Field andFieldReply()
 * @method \Cms\Model\Contact\Query\Field orFieldReply()
 * @method \Cms\Model\Contact\Query\Field orderAscReply()
 * @method \Cms\Model\Contact\Query\Field orderDescReply()
 * @method \Cms\Model\Contact\Query\Field whereCmsAuthIdReply()
 * @method \Cms\Model\Contact\Query\Field andFieldCmsAuthIdReply()
 * @method \Cms\Model\Contact\Query\Field orFieldCmsAuthIdReply()
 * @method \Cms\Model\Contact\Query\Field orderAscCmsAuthIdReply()
 * @method \Cms\Model\Contact\Query\Field orderDescCmsAuthIdReply()
 * @method \Cms\Model\Contact\Query\Field whereUri()
 * @method \Cms\Model\Contact\Query\Field andFieldUri()
 * @method \Cms\Model\Contact\Query\Field orFieldUri()
 * @method \Cms\Model\Contact\Query\Field orderAscUri()
 * @method \Cms\Model\Contact\Query\Field orderDescUri()
 * @method \Cms\Model\Contact\Query\Field whereName()
 * @method \Cms\Model\Contact\Query\Field andFieldName()
 * @method \Cms\Model\Contact\Query\Field orFieldName()
 * @method \Cms\Model\Contact\Query\Field orderAscName()
 * @method \Cms\Model\Contact\Query\Field orderDescName()
 * @method \Cms\Model\Contact\Query\Field wherePhone()
 * @method \Cms\Model\Contact\Query\Field andFieldPhone()
 * @method \Cms\Model\Contact\Query\Field orFieldPhone()
 * @method \Cms\Model\Contact\Query\Field orderAscPhone()
 * @method \Cms\Model\Contact\Query\Field orderDescPhone()
 * @method \Cms\Model\Contact\Query\Field whereEmail()
 * @method \Cms\Model\Contact\Query\Field andFieldEmail()
 * @method \Cms\Model\Contact\Query\Field orFieldEmail()
 * @method \Cms\Model\Contact\Query\Field orderAscEmail()
 * @method \Cms\Model\Contact\Query\Field orderDescEmail()
 * @method \Cms\Model\Contact\Query\Field whereIp()
 * @method \Cms\Model\Contact\Query\Field andFieldIp()
 * @method \Cms\Model\Contact\Query\Field orFieldIp()
 * @method \Cms\Model\Contact\Query\Field orderAscIp()
 * @method \Cms\Model\Contact\Query\Field orderDescIp()
 * @method \Cms\Model\Contact\Query\Field whereCmsAuthId()
 * @method \Cms\Model\Contact\Query\Field andFieldCmsAuthId()
 * @method \Cms\Model\Contact\Query\Field orFieldCmsAuthId()
 * @method \Cms\Model\Contact\Query\Field orderAscCmsAuthId()
 * @method \Cms\Model\Contact\Query\Field orderDescCmsAuthId()
 * @method \Cms\Model\Contact\Query\Field whereActive()
 * @method \Cms\Model\Contact\Query\Field andFieldActive()
 * @method \Cms\Model\Contact\Query\Field orFieldActive()
 * @method \Cms\Model\Contact\Query\Field orderAscActive()
 * @method \Cms\Model\Contact\Query\Field orderDescActive()
 * @method \Cms\Model\Contact\Query\Field andField($fieldName, $tableName = null)
 * @method \Cms\Model\Contact\Query\Field where($fieldName, $tableName = null)
 * @method \Cms\Model\Contact\Query\Field orField($fieldName, $tableName = null)
 * @method \Cms\Model\Contact\Query\Join join($tableName, $targetTableName = null)
 * @method \Cms\Model\Contact\Query\Join joinLeft($tableName, $targetTableName = null)
 * @method \Cms\Model\Contact\Record[] find()
 * @method \Cms\Model\Contact\Record findFirst()
 * @method \Cms\Model\Contact\Record findPk($value)
 */
class Query extends \Mmi\Dao\Query {

	/**
	 * @return \Cms\Model\Contact\Query
	 */
	public static function factory($daoClassName = null) {
		return new self($daoClassName);
	}

}
