<?php

namespace Cms\Model\Comment;

/**
 * @method \Cms\Model\Comment\Query limit($limit = null)
 * @method \Cms\Model\Comment\Query offset($offset = null)
 * @method \Cms\Model\Comment\Query orderAsc($fieldName, $tableName = null)
 * @method \Cms\Model\Comment\Query orderDesc($fieldName, $tableName = null)
 * @method \Cms\Model\Comment\Query andQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Comment\Query whereQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Comment\Query orQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Comment\Query resetOrder()
 * @method \Cms\Model\Comment\Query resetWhere()
 * @method \Cms\Model\Comment\Query\Field whereId()
 * @method \Cms\Model\Comment\Query\Field andFieldId()
 * @method \Cms\Model\Comment\Query\Field orFieldId()
 * @method \Cms\Model\Comment\Query\Field orderAscId()
 * @method \Cms\Model\Comment\Query\Field orderDescId()
 * @method \Cms\Model\Comment\Query\Field whereCmsAuthId()
 * @method \Cms\Model\Comment\Query\Field andFieldCmsAuthId()
 * @method \Cms\Model\Comment\Query\Field orFieldCmsAuthId()
 * @method \Cms\Model\Comment\Query\Field orderAscCmsAuthId()
 * @method \Cms\Model\Comment\Query\Field orderDescCmsAuthId()
 * @method \Cms\Model\Comment\Query\Field whereParentId()
 * @method \Cms\Model\Comment\Query\Field andFieldParentId()
 * @method \Cms\Model\Comment\Query\Field orFieldParentId()
 * @method \Cms\Model\Comment\Query\Field orderAscParentId()
 * @method \Cms\Model\Comment\Query\Field orderDescParentId()
 * @method \Cms\Model\Comment\Query\Field whereDateAdd()
 * @method \Cms\Model\Comment\Query\Field andFieldDateAdd()
 * @method \Cms\Model\Comment\Query\Field orFieldDateAdd()
 * @method \Cms\Model\Comment\Query\Field orderAscDateAdd()
 * @method \Cms\Model\Comment\Query\Field orderDescDateAdd()
 * @method \Cms\Model\Comment\Query\Field whereTitle()
 * @method \Cms\Model\Comment\Query\Field andFieldTitle()
 * @method \Cms\Model\Comment\Query\Field orFieldTitle()
 * @method \Cms\Model\Comment\Query\Field orderAscTitle()
 * @method \Cms\Model\Comment\Query\Field orderDescTitle()
 * @method \Cms\Model\Comment\Query\Field whereText()
 * @method \Cms\Model\Comment\Query\Field andFieldText()
 * @method \Cms\Model\Comment\Query\Field orFieldText()
 * @method \Cms\Model\Comment\Query\Field orderAscText()
 * @method \Cms\Model\Comment\Query\Field orderDescText()
 * @method \Cms\Model\Comment\Query\Field whereSignature()
 * @method \Cms\Model\Comment\Query\Field andFieldSignature()
 * @method \Cms\Model\Comment\Query\Field orFieldSignature()
 * @method \Cms\Model\Comment\Query\Field orderAscSignature()
 * @method \Cms\Model\Comment\Query\Field orderDescSignature()
 * @method \Cms\Model\Comment\Query\Field whereIp()
 * @method \Cms\Model\Comment\Query\Field andFieldIp()
 * @method \Cms\Model\Comment\Query\Field orFieldIp()
 * @method \Cms\Model\Comment\Query\Field orderAscIp()
 * @method \Cms\Model\Comment\Query\Field orderDescIp()
 * @method \Cms\Model\Comment\Query\Field whereStars()
 * @method \Cms\Model\Comment\Query\Field andFieldStars()
 * @method \Cms\Model\Comment\Query\Field orFieldStars()
 * @method \Cms\Model\Comment\Query\Field orderAscStars()
 * @method \Cms\Model\Comment\Query\Field orderDescStars()
 * @method \Cms\Model\Comment\Query\Field whereObject()
 * @method \Cms\Model\Comment\Query\Field andFieldObject()
 * @method \Cms\Model\Comment\Query\Field orFieldObject()
 * @method \Cms\Model\Comment\Query\Field orderAscObject()
 * @method \Cms\Model\Comment\Query\Field orderDescObject()
 * @method \Cms\Model\Comment\Query\Field whereObjectId()
 * @method \Cms\Model\Comment\Query\Field andFieldObjectId()
 * @method \Cms\Model\Comment\Query\Field orFieldObjectId()
 * @method \Cms\Model\Comment\Query\Field orderAscObjectId()
 * @method \Cms\Model\Comment\Query\Field orderDescObjectId()
 * @method \Cms\Model\Comment\Query\Field andField($fieldName, $tableName = null)
 * @method \Cms\Model\Comment\Query\Field where($fieldName, $tableName = null)
 * @method \Cms\Model\Comment\Query\Field orField($fieldName, $tableName = null)
 * @method \Cms\Model\Comment\Query\Join join($tableName, $targetTableName = null)
 * @method \Cms\Model\Comment\Query\Join joinLeft($tableName, $targetTableName = null)
 * @method \Cms\Model\Comment\Record[] find()
 * @method \Cms\Model\Comment\Record findFirst()
 * @method \Cms\Model\Comment\Record findPk($value)
 */
class Query extends \Mmi\Dao\Query {

	/**
	 * @return \Cms\Model\Comment\Query
	 */
	public static function factory($daoClassName = null) {
		return new self($daoClassName);
	}

}
