<?php

namespace Cms\Model\Cron;

/**
 * @method \Cms\Model\Cron\Query limit($limit = null)
 * @method \Cms\Model\Cron\Query offset($offset = null)
 * @method \Cms\Model\Cron\Query orderAsc($fieldName, $tableName = null)
 * @method \Cms\Model\Cron\Query orderDesc($fieldName, $tableName = null)
 * @method \Cms\Model\Cron\Query andQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Cron\Query whereQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Cron\Query orQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\Cron\Query resetOrder()
 * @method \Cms\Model\Cron\Query resetWhere()
 * @method \Cms\Model\Cron\Query\Field whereId()
 * @method \Cms\Model\Cron\Query\Field andFieldId()
 * @method \Cms\Model\Cron\Query\Field orFieldId()
 * @method \Cms\Model\Cron\Query\Field orderAscId()
 * @method \Cms\Model\Cron\Query\Field orderDescId()
 * @method \Cms\Model\Cron\Query\Field whereActive()
 * @method \Cms\Model\Cron\Query\Field andFieldActive()
 * @method \Cms\Model\Cron\Query\Field orFieldActive()
 * @method \Cms\Model\Cron\Query\Field orderAscActive()
 * @method \Cms\Model\Cron\Query\Field orderDescActive()
 * @method \Cms\Model\Cron\Query\Field whereMinute()
 * @method \Cms\Model\Cron\Query\Field andFieldMinute()
 * @method \Cms\Model\Cron\Query\Field orFieldMinute()
 * @method \Cms\Model\Cron\Query\Field orderAscMinute()
 * @method \Cms\Model\Cron\Query\Field orderDescMinute()
 * @method \Cms\Model\Cron\Query\Field whereHour()
 * @method \Cms\Model\Cron\Query\Field andFieldHour()
 * @method \Cms\Model\Cron\Query\Field orFieldHour()
 * @method \Cms\Model\Cron\Query\Field orderAscHour()
 * @method \Cms\Model\Cron\Query\Field orderDescHour()
 * @method \Cms\Model\Cron\Query\Field whereDayOfMonth()
 * @method \Cms\Model\Cron\Query\Field andFieldDayOfMonth()
 * @method \Cms\Model\Cron\Query\Field orFieldDayOfMonth()
 * @method \Cms\Model\Cron\Query\Field orderAscDayOfMonth()
 * @method \Cms\Model\Cron\Query\Field orderDescDayOfMonth()
 * @method \Cms\Model\Cron\Query\Field whereMonth()
 * @method \Cms\Model\Cron\Query\Field andFieldMonth()
 * @method \Cms\Model\Cron\Query\Field orFieldMonth()
 * @method \Cms\Model\Cron\Query\Field orderAscMonth()
 * @method \Cms\Model\Cron\Query\Field orderDescMonth()
 * @method \Cms\Model\Cron\Query\Field whereDayOfWeek()
 * @method \Cms\Model\Cron\Query\Field andFieldDayOfWeek()
 * @method \Cms\Model\Cron\Query\Field orFieldDayOfWeek()
 * @method \Cms\Model\Cron\Query\Field orderAscDayOfWeek()
 * @method \Cms\Model\Cron\Query\Field orderDescDayOfWeek()
 * @method \Cms\Model\Cron\Query\Field whereName()
 * @method \Cms\Model\Cron\Query\Field andFieldName()
 * @method \Cms\Model\Cron\Query\Field orFieldName()
 * @method \Cms\Model\Cron\Query\Field orderAscName()
 * @method \Cms\Model\Cron\Query\Field orderDescName()
 * @method \Cms\Model\Cron\Query\Field whereDescription()
 * @method \Cms\Model\Cron\Query\Field andFieldDescription()
 * @method \Cms\Model\Cron\Query\Field orFieldDescription()
 * @method \Cms\Model\Cron\Query\Field orderAscDescription()
 * @method \Cms\Model\Cron\Query\Field orderDescDescription()
 * @method \Cms\Model\Cron\Query\Field whereModule()
 * @method \Cms\Model\Cron\Query\Field andFieldModule()
 * @method \Cms\Model\Cron\Query\Field orFieldModule()
 * @method \Cms\Model\Cron\Query\Field orderAscModule()
 * @method \Cms\Model\Cron\Query\Field orderDescModule()
 * @method \Cms\Model\Cron\Query\Field whereController()
 * @method \Cms\Model\Cron\Query\Field andFieldController()
 * @method \Cms\Model\Cron\Query\Field orFieldController()
 * @method \Cms\Model\Cron\Query\Field orderAscController()
 * @method \Cms\Model\Cron\Query\Field orderDescController()
 * @method \Cms\Model\Cron\Query\Field whereAction()
 * @method \Cms\Model\Cron\Query\Field andFieldAction()
 * @method \Cms\Model\Cron\Query\Field orFieldAction()
 * @method \Cms\Model\Cron\Query\Field orderAscAction()
 * @method \Cms\Model\Cron\Query\Field orderDescAction()
 * @method \Cms\Model\Cron\Query\Field whereDateAdd()
 * @method \Cms\Model\Cron\Query\Field andFieldDateAdd()
 * @method \Cms\Model\Cron\Query\Field orFieldDateAdd()
 * @method \Cms\Model\Cron\Query\Field orderAscDateAdd()
 * @method \Cms\Model\Cron\Query\Field orderDescDateAdd()
 * @method \Cms\Model\Cron\Query\Field whereDateModified()
 * @method \Cms\Model\Cron\Query\Field andFieldDateModified()
 * @method \Cms\Model\Cron\Query\Field orFieldDateModified()
 * @method \Cms\Model\Cron\Query\Field orderAscDateModified()
 * @method \Cms\Model\Cron\Query\Field orderDescDateModified()
 * @method \Cms\Model\Cron\Query\Field whereDateLastExecute()
 * @method \Cms\Model\Cron\Query\Field andFieldDateLastExecute()
 * @method \Cms\Model\Cron\Query\Field orFieldDateLastExecute()
 * @method \Cms\Model\Cron\Query\Field orderAscDateLastExecute()
 * @method \Cms\Model\Cron\Query\Field orderDescDateLastExecute()
 * @method \Cms\Model\Cron\Query\Field andField($fieldName, $tableName = null)
 * @method \Cms\Model\Cron\Query\Field where($fieldName, $tableName = null)
 * @method \Cms\Model\Cron\Query\Field orField($fieldName, $tableName = null)
 * @method \Cms\Model\Cron\Query\Join join($tableName, $targetTableName = null)
 * @method \Cms\Model\Cron\Query\Join joinLeft($tableName, $targetTableName = null)
 * @method \Cms\Model\Cron\Record[] find()
 * @method \Cms\Model\Cron\Record findFirst()
 * @method \Cms\Model\Cron\Record findPk($value)
 */
class Query extends \Mmi\Dao\Query {

	/**
	 * @return \Cms\Model\Cron\Query
	 */
	public static function factory($daoClassName = null) {
		return new self($daoClassName);
	}

}
