<?php

namespace Cms\Model\File;

/**
 * @method \Cms\Model\File\Query limit($limit = null)
 * @method \Cms\Model\File\Query offset($offset = null)
 * @method \Cms\Model\File\Query orderAsc($fieldName, $tableName = null)
 * @method \Cms\Model\File\Query orderDesc($fieldName, $tableName = null)
 * @method \Cms\Model\File\Query andQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\File\Query whereQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\File\Query orQuery(\Mmi\Dao\Query $query)
 * @method \Cms\Model\File\Query resetOrder()
 * @method \Cms\Model\File\Query resetWhere()
 * @method \Cms\Model\File\Query\Field whereId()
 * @method \Cms\Model\File\Query\Field andFieldId()
 * @method \Cms\Model\File\Query\Field orFieldId()
 * @method \Cms\Model\File\Query\Field orderAscId()
 * @method \Cms\Model\File\Query\Field orderDescId()
 * @method \Cms\Model\File\Query\Field whereClass()
 * @method \Cms\Model\File\Query\Field andFieldClass()
 * @method \Cms\Model\File\Query\Field orFieldClass()
 * @method \Cms\Model\File\Query\Field orderAscClass()
 * @method \Cms\Model\File\Query\Field orderDescClass()
 * @method \Cms\Model\File\Query\Field whereMimeType()
 * @method \Cms\Model\File\Query\Field andFieldMimeType()
 * @method \Cms\Model\File\Query\Field orFieldMimeType()
 * @method \Cms\Model\File\Query\Field orderAscMimeType()
 * @method \Cms\Model\File\Query\Field orderDescMimeType()
 * @method \Cms\Model\File\Query\Field whereName()
 * @method \Cms\Model\File\Query\Field andFieldName()
 * @method \Cms\Model\File\Query\Field orFieldName()
 * @method \Cms\Model\File\Query\Field orderAscName()
 * @method \Cms\Model\File\Query\Field orderDescName()
 * @method \Cms\Model\File\Query\Field whereOriginal()
 * @method \Cms\Model\File\Query\Field andFieldOriginal()
 * @method \Cms\Model\File\Query\Field orFieldOriginal()
 * @method \Cms\Model\File\Query\Field orderAscOriginal()
 * @method \Cms\Model\File\Query\Field orderDescOriginal()
 * @method \Cms\Model\File\Query\Field whereTitle()
 * @method \Cms\Model\File\Query\Field andFieldTitle()
 * @method \Cms\Model\File\Query\Field orFieldTitle()
 * @method \Cms\Model\File\Query\Field orderAscTitle()
 * @method \Cms\Model\File\Query\Field orderDescTitle()
 * @method \Cms\Model\File\Query\Field whereAuthor()
 * @method \Cms\Model\File\Query\Field andFieldAuthor()
 * @method \Cms\Model\File\Query\Field orFieldAuthor()
 * @method \Cms\Model\File\Query\Field orderAscAuthor()
 * @method \Cms\Model\File\Query\Field orderDescAuthor()
 * @method \Cms\Model\File\Query\Field whereSource()
 * @method \Cms\Model\File\Query\Field andFieldSource()
 * @method \Cms\Model\File\Query\Field orFieldSource()
 * @method \Cms\Model\File\Query\Field orderAscSource()
 * @method \Cms\Model\File\Query\Field orderDescSource()
 * @method \Cms\Model\File\Query\Field whereSize()
 * @method \Cms\Model\File\Query\Field andFieldSize()
 * @method \Cms\Model\File\Query\Field orFieldSize()
 * @method \Cms\Model\File\Query\Field orderAscSize()
 * @method \Cms\Model\File\Query\Field orderDescSize()
 * @method \Cms\Model\File\Query\Field whereDateAdd()
 * @method \Cms\Model\File\Query\Field andFieldDateAdd()
 * @method \Cms\Model\File\Query\Field orFieldDateAdd()
 * @method \Cms\Model\File\Query\Field orderAscDateAdd()
 * @method \Cms\Model\File\Query\Field orderDescDateAdd()
 * @method \Cms\Model\File\Query\Field whereDateModify()
 * @method \Cms\Model\File\Query\Field andFieldDateModify()
 * @method \Cms\Model\File\Query\Field orFieldDateModify()
 * @method \Cms\Model\File\Query\Field orderAscDateModify()
 * @method \Cms\Model\File\Query\Field orderDescDateModify()
 * @method \Cms\Model\File\Query\Field whereOrder()
 * @method \Cms\Model\File\Query\Field andFieldOrder()
 * @method \Cms\Model\File\Query\Field orFieldOrder()
 * @method \Cms\Model\File\Query\Field orderAscOrder()
 * @method \Cms\Model\File\Query\Field orderDescOrder()
 * @method \Cms\Model\File\Query\Field whereSticky()
 * @method \Cms\Model\File\Query\Field andFieldSticky()
 * @method \Cms\Model\File\Query\Field orFieldSticky()
 * @method \Cms\Model\File\Query\Field orderAscSticky()
 * @method \Cms\Model\File\Query\Field orderDescSticky()
 * @method \Cms\Model\File\Query\Field whereObject()
 * @method \Cms\Model\File\Query\Field andFieldObject()
 * @method \Cms\Model\File\Query\Field orFieldObject()
 * @method \Cms\Model\File\Query\Field orderAscObject()
 * @method \Cms\Model\File\Query\Field orderDescObject()
 * @method \Cms\Model\File\Query\Field whereObjectId()
 * @method \Cms\Model\File\Query\Field andFieldObjectId()
 * @method \Cms\Model\File\Query\Field orFieldObjectId()
 * @method \Cms\Model\File\Query\Field orderAscObjectId()
 * @method \Cms\Model\File\Query\Field orderDescObjectId()
 * @method \Cms\Model\File\Query\Field whereCmsAuthId()
 * @method \Cms\Model\File\Query\Field andFieldCmsAuthId()
 * @method \Cms\Model\File\Query\Field orFieldCmsAuthId()
 * @method \Cms\Model\File\Query\Field orderAscCmsAuthId()
 * @method \Cms\Model\File\Query\Field orderDescCmsAuthId()
 * @method \Cms\Model\File\Query\Field whereActive()
 * @method \Cms\Model\File\Query\Field andFieldActive()
 * @method \Cms\Model\File\Query\Field orFieldActive()
 * @method \Cms\Model\File\Query\Field orderAscActive()
 * @method \Cms\Model\File\Query\Field orderDescActive()
 * @method \Cms\Model\File\Query\Field andField($fieldName, $tableName = null)
 * @method \Cms\Model\File\Query\Field where($fieldName, $tableName = null)
 * @method \Cms\Model\File\Query\Field orField($fieldName, $tableName = null)
 * @method \Cms\Model\File\Query\Join join($tableName, $targetTableName = null)
 * @method \Cms\Model\File\Query\Join joinLeft($tableName, $targetTableName = null)
 * @method \Cms\Model\File\Record[] find()
 * @method \Cms\Model\File\Record findFirst()
 * @method \Cms\Model\File\Record findPk($value)
 */
class Query extends \Mmi\Dao\Query {

	/**
	 * @return \Cms\Model\File\Query
	 */
	public static function factory($daoClassName = null) {
		return new self($daoClassName);
	}

}
